function run_all(graphSource)
%run_all Run all correlations and regressions for student_pipeline_3.0.
%
% run_all()             uses immutable canonical graph files (recommended).
% run_all('canonical')  same as above.
% run_all('work')       uses graphs regenerated by rerun_graphs.m.

if nargin < 1 || isempty(graphSource)
    graphSource = 'canonical';
end
graphSource = lower(char(graphSource));
assert(ismember(graphSource, {'canonical','work'}), ...
    'graphSource must be ''canonical'' or ''work''.');

rootDir = fileparts(fileparts(mfilename('fullpath')));
addpath(rootDir);
cfg = pipeline_config(graphSource);
oldSource = getenv('AQ_PIPELINE_GRAPH_SOURCE');
setenv('AQ_PIPELINE_GRAPH_SOURCE', graphSource);
restoreEnvironment = onCleanup(@() setenv( ...
    'AQ_PIPELINE_GRAPH_SOURCE', oldSource)); %#ok<NASGU>

oldDir = pwd;
restoreDirectory = onCleanup(@() cd(oldDir)); %#ok<NASGU>
cd(cfg.corrDir);

fprintf('student_pipeline_3.0 statistics\n');
fprintf('Graph source: %s\n', graphSource);
fprintf('Graph root: %s\n', cfg.graphRoot);
step1_extract_design
step2_global_corr
step3_network_corr
step4_node_corr
step5_export_plotdata
step6_hierarchical_regression
fprintf('\nALL DONE (student_pipeline_3.0, graphSource=%s).\n', graphSource);
end
